<a href="https://colab.research.google.com/github/AkshitSingh11/Autonomous-Warehouse-Robot--Q-learning/blob/main/Autonomous_Warehouse_Robot_1st_version.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Importing the dependencies

In [1]:
import numpy as np

# Setting the parameters

In [2]:
gamma = 0.75     # Discount Factor
alpha = 0.9      # learning rate

# Defining The Environment

Priority rank of the locations has been pre-defined in the question.
Priority Rank:
* 1 - G
* 2 - K
* 3 - L
* 4 - J
* 5 - A
* 6 - I
* 7 - H
* 8 - C
* 9 - B
* 10 - D
* 11 - F
* 12 - E

## Defining the States

In [3]:
location_to_state = {'A': 0,
                     'B': 1,
                     'C': 2,
                     'D': 3,
                     'E': 4,
                     'F': 5,
                     'G': 6,
                     'H': 7,
                     'I': 8,
                     'J': 9,
                     'K': 10,
                     'L': 11}

## Defining the actions

In [6]:
actions = [0,1,2,3,4,5,6,7,8,9,10,11]

## Defining the rewards

Each row corresponds to the corresponding state and each column corresponds to the corresponding action.

Since Location G has highest priority, its value is set to a higher reward, i.e. (6,6) is set to 1000 as G corresponds to row 6

In [13]:
R = np.array([[0,1,0,0,0,0,0,0,0,0,0,0],
              [1,0,1,0,0,1,0,0,0,0,0,0],
              [0,1,0,0,0,0,1,0,0,0,0,0],
              [0,0,0,0,0,0,0,1,0,0,0,0],
              [0,0,0,0,0,0,0,0,1,0,0,0],
              [0,1,0,0,0,0,0,0,0,1,0,0],
              [0,0,1,0,0,0,1000,1,0,0,0,0],
              [0,0,0,1,0,0,1,0,0,0,0,1],
              [0,0,0,0,1,0,0,0,0,1,0,0],
              [0,0,0,0,0,1,0,0,1,0,1,0],
              [0,0,0,0,0,0,0,0,0,1,0,1],
              [0,0,0,0,0,0,0,1,0,0,1,0]])

# Building the AI solution with Q-Learning

## Initializing the Q-Values

In [14]:
Q = np.array(np.zeros([12,12]))

##Q-learning Process

In [15]:
for i in range(1000):
  current_state= np.random.randint(0,12)   #choosing a random starting point
  playable_actions=[]
  for j in range(12):
    if R[current_state][j]>0:
      playable_actions.append(j)
  next_state = np.random.choice(playable_actions)   #choosing a random step
  TD = R[current_state][next_state]+ gamma*Q[next_state][np.argmax(Q[next_state,])] - Q[current_state,next_state]     # Calculating temporal difference
  Q[current_state][next_state]= Q[current_state][next_state] + alpha*TD     # Updating the Q-values in the matrix

In [16]:
print("Q-Values")
print(Q.astype(int))

Q-Values
[[   0 1681    0    0    0    0    0    0    0    0    0    0]
 [1261    0 2240    0    0 1262    0    0    0    0    0    0]
 [   0 1677    0    0    0    0 2986    0    0    0    0    0]
 [   0    0    0    0    0    0    0 2240    0    0    0    0]
 [   0    0    0    0    0    0    0    0  710    0    0    0]
 [   0 1681    0    0    0    0    0    0    0  947    0    0]
 [   0    0 2237    0    0    0 3981 2236    0    0    0    0]
 [   0    0    0 1681    0    0 2986    0    0    0    0 1681]
 [   0    0    0    0  526    0    0    0    0  945    0    0]
 [   0    0    0    0    0 1261    0    0  700    0 1261    0]
 [   0    0    0    0    0    0    0    0    0  947    0 1681]
 [   0    0    0    0    0    0    0 2240    0    0 1261    0]]


In [17]:
# Making a mapping from states to the locations
state_to_location = {state: location for location, state in location_to_state.items()}

## Function to return optimal route

In [18]:
def route(starting_location, ending_location):
  route =[starting_location]
  next_location= starting_location
  while (next_location!=ending_location):
    starting_state= location_to_state[starting_location]
    next_state = np.argmax(Q[starting_state,])      #choosing next_state
    next_location = state_to_location[next_state]
    route.append(next_location)   #appending the next location in our route array
    starting_location= next_location
  return route

# Testing our model

In [21]:
print('Route')
route('E','G')

Route


['E', 'I', 'J', 'F', 'B', 'C', 'G']

In [22]:
print('Route')
route('A','G')

Route


['A', 'B', 'C', 'G']